name: PR Status Checks

on:
  pull_request:
    branches:
      - dev

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Python script to validate PR
      run: |
        python .github/scripts/check_pr.py
